server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order
          uri: lb://microservice-order
          predicates:
            - Path=/sm/order/**	 
        - id: product
          uri: lb://microservice-product
          predicates:
            - Path=/sm/product/**

eureka:
  instance:
    hostname: localhost
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka